### ISSUE TITLE
[Investigate] createAndStartTunnel() not checking OS VPN permissions

### ISSUE THREAD

**Issue by tzeejay** [GuardianFirewall/GuardianConnect-Android#18]
Calling `createAndStartTunnel()` without first handling the VPN profile permission with Android itself will not be caught in our logic and ends up running through all the steps to create VPN credentials but ultimately fails silently. Can we add a runtime check to see if the current app is allowed to add VPN profiles without invoking the permission modal alert asking the user for the ability to add VPN profiles?

**Comment by labaiv63** [comment]
As of Android 11, the "WRITE_SECURE_SETTINGS" permission, which is required to add VPN profiles programmatically, is a system-level permission and cannot be requested or granted at runtime by third-party apps. This means that even if you check for the permission at runtime, you won't be able to get the permission without going through the permission modal alert and asking the user for the ability to add VPN profiles.

**Comment by tzeejay** [comment]
Done as of release `0.2.6`
